# Generated by Django 4.2.16 on 2025-09-03 08:54

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coletafaces',
            old_name='created_at',
            new_name='criacao',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
